name: Run Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Use the Node.js version you need
    - name: Clean install
      run: |
        rm -rf node_modules package-lock.json
        npm install
    - name: Run build
      run: npm run build
